# Generated by Django 3.2.9 on 2021-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='added_by',
        ),
    ]
